#!/bin/bash

export DRAND_SHARE_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
node_port=50000
control_port=40000


#--------------------- Generate keypair
gen_keypair () {
    id="${1}"
    scheme="${2}"
    
    ./drand_go generate-keypair --tls-disable --scheme $scheme --id $id --folder node50001 localhost:50001
    
    for ((i=2;i<=$nodes;i++))
    do
        ./drand_rs generate-keypair --tls-disable --scheme $scheme --id $id --folder $PWD/node$(expr $node_port + $i)  localhost:$(expr $node_port + $i);
    done
}


#--------------------- Start nodes
start_nodes () {
    ./drand_go start --tls-disable --folder node50001 --private-listen localhost:50001 --control 40001 > leader.log 2>&1 &
    
    ## add --tls-disable if mimic
    for ((i=2;i<=$nodes;i++))
    do
        ./drand_rs start --verbose --folder node$(expr $node_port + $i) --private-listen localhost:$(expr $node_port + $i)  --control $(expr $control_port + $i) > rs_$(expr $control_port + $i).log 2>&1 &
        sleep .1;
    done
    sleep .2
}


#--------------------- DKG
dkg () {
    id="${1}"
    
    ./drand_go share --tls-disable  --leader --nodes $nodes --threshold $nodes --period 10s  --timeout 10s  --id $id --control 40001 > leader_client.log 2>&1 &
    sleep .2
    
    for ((i=2;i<=$nodes;i++))
    do
        ./drand_rs share --tls-disable --connect localhost:50001 --id $id --control $(expr $control_port + $i) &
        sleep .2;
    done
    sleep 5
}

# Example  # Leader v1.5.8          members rs = [2]......[10]
#nodes=10  # node5000[1]..........................node5000[10]

nodes=4  # Leader v1.5.8: node5000[1]    members rs = node5000[2]..node5000[4]

#           id  scheme
gen_keypair AAA pedersen-bls-chained
gen_keypair BBB pedersen-bls-unchained
gen_keypair CCC bls-unchained-g1-rfc9380

start_nodes

#nodes=4
dkg AAA
#nodes=7
dkg BBB
#nodes=10
dkg CCC

