name: Drand

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CARGO_TERM_COLOR: always

jobs:
    build-arkworks:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install protobuf-compiler
            run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
          - name: Install Rust
            uses: actions-rs/toolchain@v1
            with:
              profile: minimal
              toolchain: stable
              override: true
              components: rustfmt, clippy
          - name: Build with arkworks
            run: cargo build --release --verbose --features arkworks
          - name: Test with arkworks
            run: cargo test --release --verbose --features arkworks
          - name: Lint with arkworks
            run: cargo clippy --release --features arkworks 
          - name: Build Docker image with arkworks
            run: docker build --build-arg FEATURES=arkworks -t drand:arkworks .

    build-blstrs:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Install protobuf-compiler
            run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
          - name: Install Rust
            uses: actions-rs/toolchain@v1
            with:
              profile: minimal
              toolchain: stable
              override: true
              components: rustfmt, clippy
          - name: Build with blstrs
            run: cargo build --release --verbose --features blstrs
          - name: Test with blstrs
            run: cargo test --release --verbose --features blstrs
          - name: Lint with blstrs
            run: cargo clippy --release --features blstrs 
          - name: Build Docker image with blstrs
            run: docker build --build-arg FEATURES=blstrs -t drand:blstrs .
